server:
  port: 9001

spring:
  application:
    name: master-data-service
  datasource:
    url: jdbc:mysql://localhost:3306/olx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true